"""initial schema

Revision ID: 017c370560ce
Revises: 
Create Date: 2026-05-01 23:30:53.067361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017c370560ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('login_user', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent')),
    sa.UniqueConstraint('login_user', name=op.f('uq_agent_login_user'))
    )
    op.create_table('device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('usb_port', sa.String(length=128), nullable=True),
    sa.Column('modem_model', sa.String(length=128), nullable=True),
    sa.Column('imei', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    op.create_index(op.f('ix_device_imei'), 'device', ['imei'], unique=True)
    op.create_index(op.f('ix_device_status'), 'device', ['status'], unique=False)
    op.create_table('holiday',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday')),
    sa.UniqueConstraint('date', 'region', name='holiday_date_region')
    )
    op.create_index(op.f('ix_holiday_date'), 'holiday', ['date'], unique=False)
    op.create_table('prompt_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_version'))
    )
    op.create_index(op.f('ix_prompt_version_is_active'), 'prompt_version', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_version_scope_id'), 'prompt_version', ['scope_id'], unique=False)
    op.create_index(op.f('ix_prompt_version_scope_type'), 'prompt_version', ['scope_type'], unique=False)
    op.create_table('sim_card',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('iccid', sa.String(length=32), nullable=False),
    sa.Column('imsi', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=24), nullable=True),
    sa.Column('carrier', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signal_strength', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sim_card')),
    sa.UniqueConstraint('imsi', name=op.f('uq_sim_card_imsi'))
    )
    op.create_index(op.f('ix_sim_card_iccid'), 'sim_card', ['iccid'], unique=True)
    op.create_index(op.f('ix_sim_card_phone_number'), 'sim_card', ['phone_number'], unique=False)
    op.create_table('voice_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=False),
    sa.Column('sample_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_model'))
    )
    op.create_table('campaign',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voice_id', sa.BigInteger(), nullable=True),
    sa.Column('default_replies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('time_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_silence_activations', sa.Integer(), nullable=False),
    sa.Column('silence_threshold_ms', sa.Integer(), nullable=False),
    sa.Column('silence_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('silence_hangup_phrase', sa.String(length=512), nullable=True),
    sa.Column('max_no_progress_seconds', sa.Integer(), nullable=True),
    sa.Column('wrap_up_max_rounds', sa.Integer(), nullable=False),
    sa.Column('wrap_up_max_seconds', sa.Integer(), nullable=False),
    sa.Column('wrap_up_closing_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interruption_whitelist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interruption_min_duration_ms', sa.Integer(), nullable=False),
    sa.Column('max_continuous_interruptions', sa.Integer(), nullable=False),
    sa.Column('continuous_interruption_strategy', sa.String(length=16), nullable=False),
    sa.Column('transfer_keyword_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transfer_intent_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_intent_threshold', sa.Float(), nullable=True),
    sa.Column('transfer_round_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_round_threshold', sa.Integer(), nullable=True),
    sa.Column('transfer_llm_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_llm_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_max_count', sa.Integer(), nullable=False),
    sa.Column('follow_up_interval_days', sa.Integer(), nullable=True),
    sa.Column('follow_up_max_count', sa.Integer(), nullable=False),
    sa.Column('do_not_call_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('do_not_call_llm_enabled', sa.Boolean(), nullable=False),
    sa.Column('do_not_call_llm_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('respect_holidays', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['do_not_call_llm_prompt_version_id'], ['prompt_version.id'], name=op.f('fk_campaign_do_not_call_llm_prompt_version_id_prompt_version'), use_alter=True),
    sa.ForeignKeyConstraint(['transfer_llm_prompt_version_id'], ['prompt_version.id'], name=op.f('fk_campaign_transfer_llm_prompt_version_id_prompt_version'), use_alter=True),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_model.id'], name=op.f('fk_campaign_voice_id_voice_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('device_sim_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('sim_card_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unbind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_device_sim_binding_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sim_card_id'], ['sim_card.id'], name=op.f('fk_device_sim_binding_sim_card_id_sim_card'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sim_binding'))
    )
    op.create_index(op.f('ix_device_sim_binding_device_id'), 'device_sim_binding', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_sim_binding_is_active'), 'device_sim_binding', ['is_active'], unique=False)
    op.create_index(op.f('ix_device_sim_binding_sim_card_id'), 'device_sim_binding', ['sim_card_id'], unique=False)
    op.create_table('callback_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_template', sa.Text(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signing_secret', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_callback_config_campaign_id_campaign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback_config'))
    )
    op.create_index(op.f('ix_callback_config_campaign_id'), 'callback_config', ['campaign_id'], unique=False)
    op.create_table('campaign_device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_campaign_device_campaign_id_campaign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_campaign_device_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_device')),
    sa.UniqueConstraint('campaign_id', 'device_id', name='campaign_device_pair')
    )
    op.create_index(op.f('ix_campaign_device_campaign_id'), 'campaign_device', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_device_device_id'), 'campaign_device', ['device_id'], unique=False)
    op.create_table('filler_set',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_filler_set_campaign_id_campaign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filler_set'))
    )
    op.create_index(op.f('ix_filler_set_campaign_id'), 'filler_set', ['campaign_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('next_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hangup_cause', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_lead_campaign_id_campaign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead'))
    )
    op.create_index(op.f('ix_lead_campaign_id'), 'lead', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_next_call_at'), 'lead', ['next_call_at'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=False)
    op.create_index(op.f('ix_lead_status'), 'lead', ['status'], unique=False)
    op.create_table('role_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('current_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('ext_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_role_config_campaign_id_campaign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_prompt_version_id'], ['prompt_version.id'], name=op.f('fk_role_config_current_prompt_version_id_prompt_version'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_config'))
    )
    op.create_index(op.f('ix_role_config_campaign_id'), 'role_config', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_role_config_kind'), 'role_config', ['kind'], unique=False)
    op.create_table('call_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('caller_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transfer_status', sa.String(length=24), nullable=False),
    sa.Column('transfer_reason', sa.String(length=255), nullable=True),
    sa.Column('wrap_up_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_call_record_campaign_id_campaign'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name=op.f('fk_call_record_lead_id_lead'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_record'))
    )
    op.create_index(op.f('ix_call_record_campaign_id'), 'call_record', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_record_lead_id'), 'call_record', ['lead_id'], unique=False)
    op.create_index(op.f('ix_call_record_status'), 'call_record', ['status'], unique=False)
    op.create_table('filler_phrase',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filler_set_id', sa.BigInteger(), nullable=False),
    sa.Column('phrase', sa.String(length=512), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filler_set_id'], ['filler_set.id'], name=op.f('fk_filler_phrase_filler_set_id_filler_set'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filler_phrase'))
    )
    op.create_index(op.f('ix_filler_phrase_filler_set_id'), 'filler_phrase', ['filler_set_id'], unique=False)
    op.create_table('call_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_record_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goal_achieved', sa.Boolean(), nullable=False),
    sa.Column('goal_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_record.id'], name=op.f('fk_call_summary_call_record_id_call_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_summary'))
    )
    op.create_index(op.f('ix_call_summary_call_record_id'), 'call_summary', ['call_record_id'], unique=True)
    op.create_table('callback_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('callback_config_id', sa.BigInteger(), nullable=False),
    sa.Column('call_record_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_code', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_record.id'], name=op.f('fk_callback_log_call_record_id_call_record'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['callback_config_id'], ['callback_config.id'], name=op.f('fk_callback_log_callback_config_id_callback_config'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback_log'))
    )
    op.create_index(op.f('ix_callback_log_call_record_id'), 'callback_log', ['call_record_id'], unique=False)
    op.create_index(op.f('ix_callback_log_callback_config_id'), 'callback_log', ['callback_config_id'], unique=False)
    op.create_index(op.f('ix_callback_log_next_retry_at'), 'callback_log', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_callback_log_status'), 'callback_log', ['status'], unique=False)
    op.create_table('handoff_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_record_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_detail', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_handoff_task_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_record.id'], name=op.f('fk_handoff_task_call_record_id_call_record'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoff_task'))
    )
    op.create_index(op.f('ix_handoff_task_agent_id'), 'handoff_task', ['agent_id'], unique=False)
    op.create_index(op.f('ix_handoff_task_call_record_id'), 'handoff_task', ['call_record_id'], unique=False)
    op.create_index(op.f('ix_handoff_task_status'), 'handoff_task', ['status'], unique=False)
    op.create_table('pipeline_trace',
    sa.Column('call_record_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('ts_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('role_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('polish_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('polish_output', sa.Text(), nullable=True),
    sa.Column('polish_duration_ms', sa.Integer(), nullable=True),
    sa.Column('polish_role_config_id', sa.BigInteger(), nullable=True),
    sa.Column('polish_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('final_selected_candidate_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_record.id'], name=op.f('fk_pipeline_trace_call_record_id_call_record'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polish_prompt_version_id'], ['prompt_version.id'], name=op.f('fk_pipeline_trace_polish_prompt_version_id_prompt_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['polish_role_config_id'], ['role_config.id'], name=op.f('fk_pipeline_trace_polish_role_config_id_role_config'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('call_record_id', 'turn_id', name=op.f('pk_pipeline_trace'))
    )
    # ### end Alembic commands ###

    # The next three FKs are declared with use_alter=True in the ORM to break
    # the campaign/role_config <-> prompt_version cycle. Autogenerate emits
    # them inline inside create_table, but PostgreSQL silently ignores those
    # in this scenario; we recreate them explicitly here.
    op.create_foreign_key(
        op.f('fk_campaign_do_not_call_llm_prompt_version_id_prompt_version'),
        'campaign', 'prompt_version',
        ['do_not_call_llm_prompt_version_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_campaign_transfer_llm_prompt_version_id_prompt_version'),
        'campaign', 'prompt_version',
        ['transfer_llm_prompt_version_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_role_config_current_prompt_version_id_prompt_version'),
        'role_config', 'prompt_version',
        ['current_prompt_version_id'], ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Mirror of the explicit FK adds in upgrade(); drop them before tearing
    # down the referencing tables so reverting on a partial DB stays clean.
    op.drop_constraint(
        op.f('fk_role_config_current_prompt_version_id_prompt_version'),
        'role_config', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_campaign_transfer_llm_prompt_version_id_prompt_version'),
        'campaign', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_campaign_do_not_call_llm_prompt_version_id_prompt_version'),
        'campaign', type_='foreignkey',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_trace')
    op.drop_index(op.f('ix_handoff_task_status'), table_name='handoff_task')
    op.drop_index(op.f('ix_handoff_task_call_record_id'), table_name='handoff_task')
    op.drop_index(op.f('ix_handoff_task_agent_id'), table_name='handoff_task')
    op.drop_table('handoff_task')
    op.drop_index(op.f('ix_callback_log_status'), table_name='callback_log')
    op.drop_index(op.f('ix_callback_log_next_retry_at'), table_name='callback_log')
    op.drop_index(op.f('ix_callback_log_callback_config_id'), table_name='callback_log')
    op.drop_index(op.f('ix_callback_log_call_record_id'), table_name='callback_log')
    op.drop_table('callback_log')
    op.drop_index(op.f('ix_call_summary_call_record_id'), table_name='call_summary')
    op.drop_table('call_summary')
    op.drop_index(op.f('ix_filler_phrase_filler_set_id'), table_name='filler_phrase')
    op.drop_table('filler_phrase')
    op.drop_index(op.f('ix_call_record_status'), table_name='call_record')
    op.drop_index(op.f('ix_call_record_lead_id'), table_name='call_record')
    op.drop_index(op.f('ix_call_record_campaign_id'), table_name='call_record')
    op.drop_table('call_record')
    op.drop_index(op.f('ix_role_config_kind'), table_name='role_config')
    op.drop_index(op.f('ix_role_config_campaign_id'), table_name='role_config')
    op.drop_table('role_config')
    op.drop_index(op.f('ix_lead_status'), table_name='lead')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_next_call_at'), table_name='lead')
    op.drop_index(op.f('ix_lead_campaign_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_filler_set_campaign_id'), table_name='filler_set')
    op.drop_table('filler_set')
    op.drop_index(op.f('ix_campaign_device_device_id'), table_name='campaign_device')
    op.drop_index(op.f('ix_campaign_device_campaign_id'), table_name='campaign_device')
    op.drop_table('campaign_device')
    op.drop_index(op.f('ix_callback_config_campaign_id'), table_name='callback_config')
    op.drop_table('callback_config')
    op.drop_index(op.f('ix_device_sim_binding_sim_card_id'), table_name='device_sim_binding')
    op.drop_index(op.f('ix_device_sim_binding_is_active'), table_name='device_sim_binding')
    op.drop_index(op.f('ix_device_sim_binding_device_id'), table_name='device_sim_binding')
    op.drop_table('device_sim_binding')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_table('voice_model')
    op.drop_index(op.f('ix_sim_card_phone_number'), table_name='sim_card')
    op.drop_index(op.f('ix_sim_card_iccid'), table_name='sim_card')
    op.drop_table('sim_card')
    op.drop_index(op.f('ix_prompt_version_scope_type'), table_name='prompt_version')
    op.drop_index(op.f('ix_prompt_version_scope_id'), table_name='prompt_version')
    op.drop_index(op.f('ix_prompt_version_is_active'), table_name='prompt_version')
    op.drop_table('prompt_version')
    op.drop_index(op.f('ix_holiday_date'), table_name='holiday')
    op.drop_table('holiday')
    op.drop_index(op.f('ix_device_status'), table_name='device')
    op.drop_index(op.f('ix_device_imei'), table_name='device')
    op.drop_table('device')
    op.drop_table('agent')
    # ### end Alembic commands ###
