# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from isales_common.proto import cloud_edge_pb2 as cloud__edge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_edge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudEdgeStub(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bidi = channel.stream_stream(
                '/isales.cloud_edge.v1.CloudEdge/Bidi',
                request_serializer=cloud__edge__pb2.Edge2Cloud.SerializeToString,
                response_deserializer=cloud__edge__pb2.Cloud2Edge.FromString,
                _registered_method=True)


class CloudEdgeServicer(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def Bidi(self, request_iterator, context):
        """Single long-lived bidirectional stream per edge process.

        Client → Server: Edge2Cloud frames (heartbeat / dial_ack / call_event /
        hardware_alert).
        Server → Client: Cloud2Edge frames (heartbeat / dial / cancel /
        config_update / rtc_credentials / remote_diag).

        Auth: client MUST send `authorization: Bearer <EDGE_DEVICE_TOKEN>` in
        initial metadata. Server binds the stream context to the edge_device_id
        derived from that token. Token validation failures close the stream with
        UNAUTHENTICATED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudEdgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bidi': grpc.stream_stream_rpc_method_handler(
                    servicer.Bidi,
                    request_deserializer=cloud__edge__pb2.Edge2Cloud.FromString,
                    response_serializer=cloud__edge__pb2.Cloud2Edge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isales.cloud_edge.v1.CloudEdge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isales.cloud_edge.v1.CloudEdge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudEdge(object):
    """=============================================================================
    Service
    =============================================================================

    """

    @staticmethod
    def Bidi(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/isales.cloud_edge.v1.CloudEdge/Bidi',
            cloud__edge__pb2.Edge2Cloud.SerializeToString,
            cloud__edge__pb2.Cloud2Edge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
